<a href="https://colab.research.google.com/github/Tariquzzaman-faisal/hatespeech/blob/main/lstm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


# Training an LSTM on the generated encodings

In [2]:
!pip install numpy

In [3]:
import csv
import numpy as np

# Specify the CSV file path
csv_file_path = "/content/drive/MyDrive/Research/Shared Task/Violence Inciting Text Detection (VITD) Bangla/embedded2.csv"

# Read the data from the CSV file
data = np.genfromtxt(csv_file_path, delimiter=',', skip_header=1)

# Split the data into `bertEmbeddings` and `labels` arrays
bertEmbeddings = data[:, :-1]
labels = data[:, -1].astype(int)

In [7]:
print(f'bertEmbeddings: {bertEmbeddings}')
print(f'labels: {labels}')

bertEmbeddings: [[-13.00299454  -0.73462087  -0.57271749 ...   5.38898468  -2.41615009
   -0.43181288]
 [-12.77867985  -2.68920445  -3.35125947 ...   0.24795489  -0.66592824
   -1.92575634]
 [-14.33217907  -7.8353014   -3.74883032 ...  -0.76926965  -1.4627775
   -2.04114509]
 ...
 [-15.2856226   -2.84475231  -2.1643548  ...   1.90715456   0.3952359
   -0.55821282]
 [-12.2387886   -3.43063974  -7.23090553 ...   6.47149897   1.32374465
   -1.50549579]
 [-13.61747932  -4.03414297  -3.02906322 ...  -5.82230282 -13.61741447
    2.46557331]]
labels: [0 1 3 ... 0 0 1]


In [8]:
from keras.utils import to_categorical

onehot_labels = to_categorical(labels)

In [10]:
print(f'Onehot labels: {onehot_labels}')

Onehot labels: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(bertEmbeddings, onehot_labels, test_size=0.2, random_state=42)

In [18]:
print(f'X_train: {X_train.shape}\n\
        y_train: {y_train.shape}\n\
        X_val: {X_val.shape}\n\
        y_val: {y_val.shape}')

X_train: (4558, 30)
        y_train: (4558, 4)
        X_val: (1140, 30)
        y_val: (1140, 4)


# passing embeddings to lstm model

In [ ]:
import numpy as np
from keras.models import Sequential
from keras.layers import LSTM, Dense
